# https://github.com/abarichello/godot-ci/blob/master/.github/workflows/godot-ci.yml
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Godot CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'releases'
      
env:
  GODOT_VERSION: 4.0.3

jobs:
  export-android-debug:
    name: Android Debug Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          lfs: true
      - name: Export Android Debug
        uses: ./.github/actions/export-project
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          export-type: 'android'
          export-name: 'test-debug.apk'
          release: false
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          lfs: true
      - name: Export Web
        uses: ./.github/actions/export-project
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          export-type: 'web'
          export-name: 'index.html'
          release: false
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          lfs: true
      - name: Export Windows
        uses: ./.github/actions/export-project
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          export-type: 'windows'
          export-name: 'ASlimeInTheDark.exe'
          release: false
  
